const productVisuals={x3:`<svg class="product-svg" viewBox="0 0 150 100" aria-label="X3电动升降桌示意图"><rect class="body" x="14" y="35" width="122" height="12" rx="5"/><rect class="dark" x="25" y="47" width="8" height="39" rx="3"/><rect class="dark" x="117" y="47" width="8" height="39" rx="3"/><rect class="dark" x="58" y="16" width="34" height="21" rx="4"/><rect x="63" y="21" width="24" height="11" rx="2" fill="#101411"/><rect class="dark" x="72" y="37" width="6" height="12" rx="2"/><rect class="accent" x="126" y="38" width="6" height="4" rx="2"/></svg>`,tx01:`<svg class="product-svg" viewBox="0 0 150 100" aria-label="TX01显示器支架示意图"><rect x="18" y="20" width="65" height="40" rx="5" fill="#1c211e" stroke="#727d77" stroke-width="3"/><path d="M83 41h19l15-17" class="edge" stroke-width="7" stroke-linecap="round"/><path d="M102 41l14 22" class="edge" stroke-width="7" stroke-linecap="round"/><rect class="dark" x="112" y="61" width="11" height="27" rx="4"/><rect class="accent" x="116" y="67" width="3" height="9" rx="1.5"/></svg>`,cx9:`<svg class="product-svg" viewBox="0 0 150 100" aria-label="CX9屏幕挂灯示意图"><rect x="37" y="40" width="76" height="38" rx="6" fill="#171d1a" stroke="#6f7974" stroke-width="3"/><rect x="48" y="24" width="54" height="6" rx="3" fill="#d4ddd8"/><path d="M75 30v10" stroke="#59645e" stroke-width="5" stroke-linecap="round"/><circle class="accent" cx="106" cy="27" r="2.5"/></svg>`};
const deviceData={
x3:{name:'X3 电动升降桌',visual:'x3',model:'X3-B-A',channel:'天猫旗舰店',date:'2026年8月18日',order:'T20260818-92831',warranty:'质保中 · 至2031年8月18日'},
tx01:{name:'TX01 显示器支架',visual:'tx01',model:'TX01',channel:'京东旗舰店',date:'2026年3月12日',order:'JD20260312-58102',warranty:'质保中'},
cx9:{name:'CX9 屏幕挂灯',visual:'cx9',model:'CX9-B-A',channel:'天猫旗舰店',date:'2026年6月20日',order:'T20260620-33817',warranty:'质保中'}
};
const setupMembership={x3:true,tx01:true,cx9:false};
const serviceRecords={
 x3:[['2026.08.18','购买设备','天猫旗舰店订单已同步至会员账户'],['2026.08.18','设备绑定','自动建立设备档案并录入质保信息'],['2026.08.20','安装咨询','查看升降桌安装与初始化教程'],['2026.09.02','延保登记','完成会员延保登记']],
 tx01:[['2026.03.12','购买设备','京东旗舰店订单已同步'],['2026.03.13','设备绑定','加入Nikki的桌搭档案'],['2026.03.15','安装咨询','查看双屏安装与承重说明']],
 cx9:[['2026.06.20','购买设备','天猫旗舰店订单已同步'],['2026.06.20','设备绑定','设备已进入“我的设备”，尚未加入桌搭'],['2026.07.04','配件更换','完成夹具配件补发记录']]
};
function renderDeviceList(){const list=document.getElementById('deviceList');if(!list)return;list.innerHTML=Object.entries(deviceData).map(([k,d])=>{const joined=setupMembership[k];return `<div class="card device-card" onclick="openDevice('${k}')"><div class="device-top"><div class="thumb">${productVisuals[d.visual]}</div><div style="flex:1"><div class="device-name">${d.name}</div><div class="status">${d.warranty.split(' · ')[0]}</div><div class="meta">${d.channel} · ${d.date}${k==='x3'?'<br>质保有效期：至2031年8月18日':''}</div><div class="device-setup-state ${joined?'joined':'pending'}">${joined?'已加入Nikki的桌搭':'尚未加入桌搭'}</div>${!joined?`<button class="add-to-setup" onclick="event.stopPropagation();addToSetup('${k}')">＋ 添加到我的桌搭</button>`:''}</div></div><div class="quick"><button onclick="event.stopPropagation();openDevice('${k}')">查看设备</button><button onclick="event.stopPropagation();toast('打开安装教程')">安装教程</button><button onclick="event.stopPropagation();toast('进入售后服务')">售后服务</button><button onclick="event.stopPropagation();toast('查看适配配件方案')">适配配件</button></div></div>`}).join('');}
function addToSetup(k){setupMembership[k]=true;if(previewItems[k]){previewItems[k].owned=true;previewItems[k].active=true}renderDeviceList();renderSetupMap();renderAssessment();updateSetupCounts();renderPreviewToolbar();toast(deviceData[k].name+' 已加入Nikki的桌搭');}
function updateSetupCounts(){const n=Object.values(setupMembership).filter(Boolean).length;const a=document.getElementById('setupDeviceCount'),b=document.getElementById('setupInfoCount');if(a)a.textContent=n+'件设备已加入桌搭';if(b)b.textContent=n+'件已加入 / 3件已购';}
let previewMode=false;
const previewDefaults={monitors:{x:50,y:42,owned:true,active:true,type:'monitors',label:'双27英寸显示器'},arm:{x:50,y:54,owned:true,active:true,type:'arm',label:'TX01 显示器支架'},light:{x:50,y:29,owned:true,active:false,type:'light',label:'CX9 屏幕挂灯'},board:{x:83,y:31,owned:false,active:false,type:'board',label:'洞洞板'},mic:{x:15,y:49,owned:false,active:false,type:'mic',label:'麦克风设备'},storage:{x:79,y:62,owned:false,active:false,type:'storage',label:'桌面收纳'},cable:{x:50,y:85,owned:false,active:false,type:'cable',label:'桌下理线'}};
let previewItems={};
function loadPreview(){previewItems=JSON.parse(JSON.stringify(previewDefaults));previewItems.light.active=!!setupMembership.cx9;try{const saved=JSON.parse(localStorage.getItem('songnengPreviewLayout')||'null');if(saved&&saved.items){Object.keys(previewItems).forEach(k=>{if(saved.items[k])previewItems[k]={...previewItems[k],...saved.items[k]}})}}catch(e){}}
loadPreview();
const snapRules={monitors:[[36,42],[50,42],[64,42]],arm:[[42,54],[50,54],[58,54]],light:[[36,29],[50,29],[64,29]],board:[[17,31],[83,31]],mic:[[14,49],[86,49]],storage:[[22,62],[78,62]],cable:[[38,85],[50,85],[62,85]]};
function togglePreviewMode(){previewMode=!previewMode;const btn=document.getElementById('previewToggle'),controls=document.getElementById('previewControls'),sub=document.getElementById('setupMapSubtitle'),legend=document.getElementById('mapLegend');if(btn)btn.textContent=previewMode?'退出预演':'进入桌搭预演';if(controls)controls.classList.toggle('show',previewMode);if(sub)sub.textContent=previewMode?'按住设备拖动，松手后自动吸附到合理位置':'真实桌搭以实心显示，可完善位置以虚线显示';if(legend)legend.innerHTML=previewMode?'<span><i class="legend-dot"></i>已拥有 / 已配置</span><span><i class="legend-dash"></i>预演装备</span>':'<span><i class="legend-dot"></i>当前桌搭设备</span><span><i class="legend-dash"></i>可完善位置</span>';renderSetupMap();renderPreviewToolbar();}
function renderPreviewToolbar(){const box=document.getElementById('previewToolbar');if(!box)return;const order=['light','board','mic','storage','cable'];box.innerHTML=order.map(k=>{const i=previewItems[k];const owned=k==='light'&&setupMembership.cx9;return `<button class="gear-chip ${owned?'owned':''} ${i.active?'active':''}" onclick="togglePreviewItem('${k}')"><b>${i.label}</b><span>${owned?'已拥有':'待配置'}</span><span class="tiny-state">${i.active?'已放入预演':'点此加入预演'}</span></button>`}).join('');}
function togglePreviewItem(k){const i=previewItems[k];i.active=!i.active;if(k==='light')i.owned=!!setupMembership.cx9;renderSetupMap();renderPreviewToolbar();toast(i.active?i.label+' 已加入预演':i.label+' 已从预演移除');}
function renderSetupMap(){const map=document.getElementById('setupMap');if(!map)return;const lightJoined=setupMembership.cx9;if(!previewMode){map.classList.remove('previewing');map.innerHTML=`<div class="wall-panel"></div><div class="screen a"></div><div class="screen b"></div><div class="arm-stand"></div><div class="${lightJoined?'lightbar-solid':'lightbar-pending'}"></div><div class="desk-top"></div><div class="desk-foot l"></div><div class="desk-foot r"></div><div class="map-label label-light">${lightJoined?'CX9 屏幕挂灯':'CX9 已购 · 待加入桌搭'}</div><div class="map-label label-arm">TX01 双屏支架</div><div class="map-label label-desk">X3 电动升降桌</div><div class="ghost-zone ghost-board" onclick="solution('board')">洞洞板<br>可完善位置</div><div class="ghost-zone ghost-mic" onclick="solution('mic')">麦克风<br>设备位</div><div class="ghost-zone ghost-storage" onclick="solution('storage')">桌面收纳</div><div class="ghost-zone ghost-cable" onclick="solution('cable')">桌下理线</div>`;return;}previewItems.light.owned=lightJoined;if(lightJoined&&!previewItems.light.active)previewItems.light.active=true;map.classList.add('previewing');map.innerHTML=`<div class="wall-panel"></div><div class="preview-desk-base"></div><div class="preview-desk-leg l"></div><div class="preview-desk-leg r"></div>${Object.keys(snapRules).flatMap(k=>snapRules[k].map((p,idx)=>`<div class="snap-hint" data-snap="${k}-${idx}" style="left:${p[0]}%;top:${p[1]}%"></div>`)).join('')}${Object.entries(previewItems).filter(([k,i])=>i.active).map(([k,i])=>previewItemHTML(k,i)).join('')}<div class="preview-empty-tip">桌面为固定基准，设备与配件可拖动预演</div>`;bindPreviewDrag();}
function previewItemHTML(k,i){const cls=`preview-item ${i.owned?'owned':'simulated'} preview-${i.type}`;let inner='';if(i.type==='monitors')inner='<div class="pm-screen"></div><div class="pm-screen"></div>';return `<div class="${cls}" data-preview-key="${k}" style="left:${i.x}%;top:${i.y}%">${inner}<span class="preview-tag">${i.label}</span></div>`;}
function bindPreviewDrag(){const map=document.getElementById('setupMap');if(!map)return;map.querySelectorAll('.preview-item').forEach(el=>{el.addEventListener('pointerdown',e=>startPreviewDrag(e,el),{passive:false});});}
function startPreviewDrag(e,el){e.preventDefault();const map=document.getElementById('setupMap'),key=el.dataset.previewKey,rect=map.getBoundingClientRect();el.classList.add('dragging');el.setPointerCapture?.(e.pointerId);const move=ev=>{ev.preventDefault();let x=(ev.clientX-rect.left)/rect.width*100,y=(ev.clientY-rect.top)/rect.height*100;x=Math.max(7,Math.min(93,x));y=Math.max(13,Math.min(90,y));el.style.left=x+'%';el.style.top=y+'%';previewItems[key].x=x;previewItems[key].y=y;highlightNearestSnap(key,x,y);};const up=ev=>{el.classList.remove('dragging');window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);snapPreviewItem(key,el);clearSnapHints();};window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',up,{once:true});}
function nearestSnap(k,x,y){const pts=snapRules[k]||[[x,y]];let best=pts[0],dist=Infinity,index=0;pts.forEach((p,i)=>{const d=Math.hypot(p[0]-x,(p[1]-y)*1.2);if(d<dist){dist=d;best=p;index=i}});return {p:best,index};}
function highlightNearestSnap(k,x,y){clearSnapHints();const n=nearestSnap(k,x,y);const h=document.querySelector(`[data-snap="${k}-${n.index}"]`);if(h)h.classList.add('active')}
function clearSnapHints(){document.querySelectorAll('.snap-hint.active').forEach(x=>x.classList.remove('active'))}
function snapPreviewItem(k,el){const n=nearestSnap(k,previewItems[k].x,previewItems[k].y);previewItems[k].x=n.p[0];previewItems[k].y=n.p[1];el.style.left=n.p[0]+'%';el.style.top=n.p[1]+'%';toast(previewItems[k].label+' 已吸附到建议位置')}
function resetPreview(){localStorage.removeItem('songnengPreviewLayout');loadPreview();renderSetupMap();renderPreviewToolbar();const s=document.getElementById('previewSaveState');if(s){s.textContent='尚未保存预演方案';s.classList.remove('saved')}toast('已恢复默认预演布局');}
function savePreview(){try{localStorage.setItem('songnengPreviewLayout',JSON.stringify({items:previewItems,updatedAt:new Date().toISOString()}))}catch(e){}const s=document.getElementById('previewSaveState');if(s){s.textContent='预演方案已保存在本机 · 不改变真实桌搭';s.classList.add('saved')}toast('预演方案已保存');}