function renderAssessment(){
  const box=document.getElementById('assessmentList'); if(!box)return;
  const light=setupMembership.cx9;
  const items=[
    ['人体工学','基础条件较完整','已加入升降桌与双屏显示器支架，具备坐站切换和屏幕位置调节基础。','下一步：确认屏幕上沿高度、视距和常用桌面高度是否符合个人习惯。','good'],
    ['桌面整洁','待评估','当前档案暂无桌面照片，也没有线材与常用物品摆放信息。','下一步：补充一张桌面正面照片后，再判断收纳与理线问题。',''],
    ['灯光环境',light?'已具备屏幕照明':'待评估',light?'CX9 屏幕挂灯已加入当前桌搭，但尚未记录环境光与夜间使用情况。':'CX9 已购买但尚未加入桌搭，无法确认当前照明配置。',light?'下一步：补充环境光使用习惯，判断是否需要氛围灯或补光。':'下一步：先将CX9加入桌搭，或补充当前灯光设备信息。',light?'good':''],
    ['设备扩展','存在明确扩展位','空间图中麦克风位、洞洞板位仍为空缺，桌下理线也尚未配置。','下一步：按实际使用场景选择一个优先完善方向，不以“买更多”为目标。','']
  ];
  box.innerHTML=items.map(x=>`<div class="assessment-item"><div class="assessment-head"><div class="assessment-name">${x[0]}</div><div class="assessment-state ${x[4]}">${x[1]}</div></div><div class="assessment-copy"><div><b>判断依据：</b>${x[2]}</div><div class="next-step"><b>建议：</b>${x[3]}</div></div></div>`).join('');
}
const solutionData={
 board:{title:'洞洞板桌搭解决方案',why:'你的双屏已经占据主要横向桌面空间，右侧墙面仍有垂直空间。把低频但需要随手取用的耳机、手柄和配件上墙，可以减少桌面堆叠。',fit:'适合160×70cm桌面；建议布置在右侧墙面/桌侧，避开显示器摆动范围。',product:'松能X 洞洞板系统',desc:'以模块化挂件承接耳机、手柄与桌搭小物。'},
 mic:{title:'麦克风设备桌搭解决方案',why:'你的桌搭同时覆盖游戏与办公场景，如果存在语音、会议或直播需求，独立麦克风位能减少临时设备占桌面的问题。',fit:'建议布置在桌面左前侧，通过悬臂从侧面进入，不遮挡双屏。',product:'松能X 麦克风悬臂方案',desc:'侧边安装，减少桌面占用并保持拾音距离。'},
 storage:{title:'桌面收纳桌搭解决方案',why:'双屏桌面通常会把键鼠、充电设备和常用小物集中在中部区域，容易形成视觉杂乱。',fit:'优先优化右侧常用物品区，并结合桌下抽屉或小型收纳模块。',product:'松能X 桌面收纳方案',desc:'按高频/低频物品分区，保持主操作区留白。'},
 cable:{title:'桌下理线桌搭解决方案',why:'升降桌在上下移动时，线材需要跟随桌面运动。没有独立理线路径时，更容易出现拉扯、悬垂和视觉杂乱。',fit:'建议沿桌板底部建立固定走线路径，并为升降行程预留活动余量。',product:'松能X 桌下理线方案',desc:'围绕电源、显示器与桌面设备建立统一走线路径。'}
};
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');const mains=['home','devices','setup','me'];document.getElementById('nav').style.display=mains.includes(id)?'grid':'none';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===id));window.scrollTo(0,0);}
function show(id){document.getElementById(id).classList.add('show')}
function hide(id){document.getElementById(id).classList.remove('show')}
let tt;function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),1700)}
function mock(x){hide('addModal');toast(x+'：已完成模拟操作')}
function mockBind(x){hide('bindModal');toast('已模拟绑定：'+x)}
function editSetup(){document.getElementById('gtitle').textContent='编辑桌搭信息';document.getElementById('gcontent').innerHTML='原型中可编辑：桌面尺寸、显示器数量与尺寸、主要使用场景。<br><br>保存后可重新计算桌搭档案完整度与健康度。';show('genericModal')}
function solution(key){const s=solutionData[key];document.getElementById('gtitle').textContent=s.title;document.getElementById('gcontent').innerHTML=`<div class="solution-section"><b>为什么这个位置值得完善</b>${s.why}</div><div class="solution-section"><b>适配思路</b>${s.fit}</div><div class="solution-section"><b>适配方案与产品</b><div class="solution-product"><div class="mini-visual">${key==='board'?productVisuals.tx01:key==='mic'?productVisuals.tx01:productVisuals.x3}</div><div><strong>${s.product}</strong><span>${s.desc}</span></div></div></div><div class="solution-section" style="color:#8f9b94">这里表达的是“解决桌面问题 → 给出适配方案 → 再承接产品”，而不是直接进入商品推荐。</div>`;show('genericModal')}
function openDevice(k){const d=deviceData[k];const records=serviceRecords[k]||[];document.getElementById('detailContent').innerHTML=`<div class="card"><div class="detail-img">${productVisuals[d.visual]}</div><div style="font-size:21px;font-weight:900;margin-top:13px;text-align:center">${d.name}</div><div style="text-align:center"><span class="status">${d.warranty}</span></div><div class="detail-grid"><div class="field"><span>产品型号</span><b>${d.model}</b></div><div class="field"><span>购买日期</span><b>${d.date}</b></div><div class="field"><span>购买渠道</span><b>${d.channel}</b></div><div class="field"><span>订单号</span><b>${d.order}</b></div></div></div><div class="section"><div class="card"><div class="section-title" style="font-size:15px;margin-bottom:12px">设备服务记录</div><div class="timeline">${records.map((r,i)=>`<div class="timeline-item ${i===records.length-1?'current':''}"><span class="timeline-dot"></span><div class="timeline-time">${r[0]}</div><div class="timeline-title">${r[1]}</div><div class="timeline-desc">${r[2]}</div></div>`).join('')}</div></div></div><div class="section"><div class="card"><div class="link" onclick="toast('打开设备说明书')">设备说明书 <span>›</span></div><div class="link" onclick="toast('打开安装视频')">安装视频 <span>›</span></div><div class="link" onclick="toast('查看常见问题')">常见问题 <span>›</span></div><div class="link" onclick="toast('进入售后申请流程')">申请售后 <span>›</span></div><div class="link" style="border:0" onclick="toast('查看该设备适配方案')">适配配件 <span>›</span></div></div><div class="sub" style="margin-top:9px">设备详情页围绕“已拥有设备”的生命周期管理展开：购买、绑定、质保、咨询、售后和配件记录都沉淀在同一档案中。</div></div>`;go('detail');}
renderDeviceList();renderSetupMap();renderAssessment();updateSetupCounts();renderPreviewToolbar();
const qs=[['你的桌面尺寸？',['120×60cm','140×70cm','160×70cm','180cm及以上']],['你使用几台显示器？',['1台','2台','3台','4台及以上']],['主要显示器尺寸？',['24英寸及以下','27英寸','32英寸','超宽屏 / 49英寸']],['主要使用场景？',['办公','游戏','办公 + 游戏','直播 / 创作']],['是否使用麦克风？',['不使用','偶尔使用','经常使用','计划增加']],['是否有台式主机？',['没有','桌面放置','桌下放置','计划增加']],['是否需要大量收纳？',['不需要','少量','中等','大量']]];
let qi=0,ans=[];
function renderQuiz(){const box=document.getElementById('quiz');document.getElementById('qfill').style.width=(qi/qs.length*100)+'%';if(qi>=qs.length){box.innerHTML=`<div class="kicker">模拟诊断结果</div><div class="score">78</div><div style="font-size:16px;font-weight:850">整体桌搭成熟度较高</div><div class="sub" style="margin-top:8px">核心设备已经比较完整，下一阶段建议优先优化收纳和设备扩展。</div><div class="tip" style="margin-top:14px"><b>建议1 · 桌面收纳</b><br>增加桌下理线与垂直收纳，减少双屏场景下的桌面占用。<br><br><b>建议2 · 麦克风设备</b><br>如果存在游戏、会议或直播需求，可增加悬臂式麦克风方案。<br><br><b>建议3 · 设备联动</b><br>现有升降桌 + 显示器支架结构较完整，可继续围绕人体工学优化。</div><button class="btn primary" onclick="qi=0;ans=[];renderQuiz()">重新诊断</button><button class="btn secondary" onclick="go('setup')">返回我的桌搭</button>`;document.getElementById('qfill').style.width='100%';return}const q=qs[qi];box.innerHTML=`<div class="sub">问题 ${qi+1} / ${qs.length}</div><div style="font-size:20px;font-weight:850;margin-top:6px">${q[0]}</div><div class="qgrid">${q[1].map((x,i)=>`<button class="choice" onclick="choose(${i},this)">${x}</button>`).join('')}</div>`;}
function choose(i,el){ans[qi]=qs[qi][1][i];document.querySelectorAll('.choice').forEach(x=>x.classList.remove('sel'));el.classList.add('sel');setTimeout(()=>{qi++;renderQuiz()},170)}
renderQuiz();